{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prafka.serviceAccountName" . }}
  labels:
{{ include "prafka.labels" . | nindent 4 }}
{{- end -}}
